ALTER TABLE `tags` ADD `category_group_id` text REFERENCES categories(id);--> statement-breakpoint
CREATE INDEX `tags_kind_group_active` ON `tags` (`kind`,`category_group_id`,`is_active`);--> statement-breakpoint
INSERT INTO categories (id, slug, name, description, sort_order, is_active) VALUES ('cat_writing', 'writing', 'Writing & Language', 'Writing, editing, translation, and language workflows.', 1, 1) ON CONFLICT(slug) DO UPDATE SET name = excluded.name, description = excluded.description, sort_order = excluded.sort_order, is_active = excluded.is_active;--> statement-breakpoint
INSERT INTO categories (id, slug, name, description, sort_order, is_active) VALUES ('cat_image', 'image', 'Image & Design', 'Image generation, editing, branding, and visual design tools.', 2, 1) ON CONFLICT(slug) DO UPDATE SET name = excluded.name, description = excluded.description, sort_order = excluded.sort_order, is_active = excluded.is_active;--> statement-breakpoint
INSERT INTO categories (id, slug, name, description, sort_order, is_active) VALUES ('cat_video', 'video', 'Video & Animation', 'Video creation, recording, editing, animation, and publishing tools.', 3, 1) ON CONFLICT(slug) DO UPDATE SET name = excluded.name, description = excluded.description, sort_order = excluded.sort_order, is_active = excluded.is_active;--> statement-breakpoint
INSERT INTO categories (id, slug, name, description, sort_order, is_active) VALUES ('cat_audio', 'audio', 'Voice & Speech', 'Dictation, transcription, dubbing, speech synthesis, and voice tools.', 4, 1) ON CONFLICT(slug) DO UPDATE SET name = excluded.name, description = excluded.description, sort_order = excluded.sort_order, is_active = excluded.is_active;--> statement-breakpoint
INSERT INTO categories (id, slug, name, description, sort_order, is_active) VALUES ('cat_music', 'music', 'Music & Audio', 'Music generation, audio production, sound editing, and podcast tools.', 5, 1) ON CONFLICT(slug) DO UPDATE SET name = excluded.name, description = excluded.description, sort_order = excluded.sort_order, is_active = excluded.is_active;--> statement-breakpoint
INSERT INTO categories (id, slug, name, description, sort_order, is_active) VALUES ('cat_coding', 'coding', 'Coding & Development', 'Software development, testing, deployment, and developer tooling.', 6, 1) ON CONFLICT(slug) DO UPDATE SET name = excluded.name, description = excluded.description, sort_order = excluded.sort_order, is_active = excluded.is_active;--> statement-breakpoint
INSERT INTO categories (id, slug, name, description, sort_order, is_active) VALUES ('cat_agents', 'agents', 'Automation & Agents', 'Agents and automation systems that carry out multi-step work.', 7, 1) ON CONFLICT(slug) DO UPDATE SET name = excluded.name, description = excluded.description, sort_order = excluded.sort_order, is_active = excluded.is_active;--> statement-breakpoint
INSERT INTO categories (id, slug, name, description, sort_order, is_active) VALUES ('cat_productivity', 'productivity', 'Productivity', 'Tools for organizing work, meetings, and everyday workflows.', 8, 1) ON CONFLICT(slug) DO UPDATE SET name = excluded.name, description = excluded.description, sort_order = excluded.sort_order, is_active = excluded.is_active;--> statement-breakpoint
INSERT INTO categories (id, slug, name, description, sort_order, is_active) VALUES ('cat_research', 'research', 'Research & Data', 'Research, document analysis, data work, and source-backed discovery.', 9, 1) ON CONFLICT(slug) DO UPDATE SET name = excluded.name, description = excluded.description, sort_order = excluded.sort_order, is_active = excluded.is_active;--> statement-breakpoint
INSERT INTO categories (id, slug, name, description, sort_order, is_active) VALUES ('cat_marketing', 'marketing', 'Marketing & Sales', 'Campaign, advertising, social media, sales, and audience tools.', 10, 1) ON CONFLICT(slug) DO UPDATE SET name = excluded.name, description = excluded.description, sort_order = excluded.sort_order, is_active = excluded.is_active;--> statement-breakpoint
INSERT INTO categories (id, slug, name, description, sort_order, is_active) VALUES ('cat_business', 'business', 'Business & Operations', 'Customer support, finance, legal operations, and team management tools.', 11, 1) ON CONFLICT(slug) DO UPDATE SET name = excluded.name, description = excluded.description, sort_order = excluded.sort_order, is_active = excluded.is_active;--> statement-breakpoint
INSERT INTO categories (id, slug, name, description, sort_order, is_active) VALUES ('cat_education', 'education', 'Education & Learning', 'Teaching, studying, course creation, and language-learning tools.', 12, 1) ON CONFLICT(slug) DO UPDATE SET name = excluded.name, description = excluded.description, sort_order = excluded.sort_order, is_active = excluded.is_active;--> statement-breakpoint
INSERT INTO categories (id, slug, name, description, sort_order, is_active) VALUES ('cat_lifestyle', 'lifestyle', 'Personal & Lifestyle', 'Personal creativity, gifts, travel, wellness, and everyday-life tools.', 13, 1) ON CONFLICT(slug) DO UPDATE SET name = excluded.name, description = excluded.description, sort_order = excluded.sort_order, is_active = excluded.is_active;--> statement-breakpoint
INSERT INTO categories (id, slug, name, description, sort_order, is_active) VALUES ('cat_other', 'other', 'Other', 'Internal fallback for products awaiting classification.', 14, 0) ON CONFLICT(slug) DO UPDATE SET name = excluded.name, description = excluded.description, sort_order = excluded.sort_order, is_active = excluded.is_active;--> statement-breakpoint
UPDATE tags SET kind = 'category', category_group_id = 'cat_audio' WHERE slug IN ('dictation', 'transcription', 'dubbing', 'voice-generation');--> statement-breakpoint
UPDATE tags SET kind = 'category', category_group_id = 'cat_writing' WHERE slug = 'translation';--> statement-breakpoint
UPDATE tags SET kind = 'category', category_group_id = 'cat_image' WHERE slug IN ('image-generation', 'image-editing', 'brand-design');--> statement-breakpoint
UPDATE tags SET kind = 'category', category_group_id = 'cat_video' WHERE slug IN ('video-generation', 'video-editing', 'screen-recording');--> statement-breakpoint
UPDATE tags SET kind = 'category', category_group_id = 'cat_music' WHERE slug = 'music-generation';--> statement-breakpoint
UPDATE tags SET kind = 'category', category_group_id = 'cat_coding' WHERE slug IN ('coding-assistant', 'app-builder', 'software-testing', 'devops-monitoring');--> statement-breakpoint
UPDATE tags SET kind = 'category', category_group_id = 'cat_productivity' WHERE slug IN ('meeting-assistant', 'scheduling', 'knowledge-management');--> statement-breakpoint
UPDATE tags SET kind = 'category', category_group_id = 'cat_agents' WHERE slug = 'workflow-automation';--> statement-breakpoint
UPDATE tags SET kind = 'category', category_group_id = 'cat_marketing' WHERE slug IN ('ad-creative', 'social-media');--> statement-breakpoint
UPDATE tags SET kind = 'category', category_group_id = 'cat_research' WHERE slug IN ('business-research', 'legal-research', 'document-analysis');--> statement-breakpoint
UPDATE tags SET kind = 'category', category_group_id = 'cat_business' WHERE slug = 'customer-support';--> statement-breakpoint
UPDATE tags SET kind = 'category', category_group_id = 'cat_lifestyle' WHERE slug = 'personalized-gifts';--> statement-breakpoint
UPDATE tags SET kind = 'attribute', category_group_id = NULL WHERE slug = 'local-ai';--> statement-breakpoint
INSERT INTO tags (id, slug, name, kind, category_group_id, description, is_active) VALUES ('tag_local_models', 'local-models', 'Local models', 'category', 'cat_coding', 'Run and manage AI models on local hardware.', 1);--> statement-breakpoint
UPDATE tools SET primary_category_id = 'cat_audio' WHERE canonical_domain IN ('zenproducts.ai', 'lispr.ai');--> statement-breakpoint
UPDATE tool_categories SET is_primary = CASE WHEN category_id = 'cat_audio' THEN 1 ELSE 0 END WHERE tool_id IN (SELECT id FROM tools WHERE canonical_domain IN ('zenproducts.ai', 'lispr.ai'));--> statement-breakpoint
UPDATE tools SET primary_category_id = 'cat_coding' WHERE canonical_domain = 'lumichats.com';--> statement-breakpoint
UPDATE tool_categories SET is_primary = CASE WHEN category_id = 'cat_coding' THEN 1 ELSE 0 END WHERE tool_id IN (SELECT id FROM tools WHERE canonical_domain = 'lumichats.com');--> statement-breakpoint
INSERT OR IGNORE INTO tool_tags (tool_id, tag_id) SELECT id, 'tag_local_models' FROM tools WHERE canonical_domain = 'lumichats.com';--> statement-breakpoint
UPDATE tools SET primary_category_id = 'cat_music' WHERE canonical_domain = 'yoursonggift.net';--> statement-breakpoint
UPDATE tool_categories SET is_primary = 0 WHERE tool_id IN (SELECT id FROM tools WHERE canonical_domain = 'yoursonggift.net');--> statement-breakpoint
INSERT OR IGNORE INTO tool_categories (tool_id, category_id, is_primary) SELECT id, 'cat_music', 1 FROM tools WHERE canonical_domain = 'yoursonggift.net';
