-- Browse categories for groups that had one or none, so imports can classify
-- writing, music, education, business, marketing and lifestyle products.
INSERT INTO tags (id, slug, name, kind, category_group_id, description, is_active) VALUES ('tag_writing_assistant', 'writing-assistant', 'Writing assistant', 'category', 'cat_writing', 'Check, edit, rewrite, and polish everyday writing.', 1) ON CONFLICT(slug) DO UPDATE SET name = excluded.name, kind = excluded.kind, category_group_id = excluded.category_group_id, description = excluded.description, is_active = 1;--> statement-breakpoint
INSERT INTO tags (id, slug, name, kind, category_group_id, description, is_active) VALUES ('tag_creative_writing', 'creative-writing', 'Creative writing', 'category', 'cat_writing', 'Draft fiction, scripts, and other long-form creative work.', 1) ON CONFLICT(slug) DO UPDATE SET name = excluded.name, kind = excluded.kind, category_group_id = excluded.category_group_id, description = excluded.description, is_active = 1;--> statement-breakpoint
INSERT INTO tags (id, slug, name, kind, category_group_id, description, is_active) VALUES ('tag_content_writing', 'content-writing', 'Content writing', 'category', 'cat_writing', 'Produce articles, marketing copy, and on-brand content at scale.', 1) ON CONFLICT(slug) DO UPDATE SET name = excluded.name, kind = excluded.kind, category_group_id = excluded.category_group_id, description = excluded.description, is_active = 1;--> statement-breakpoint
INSERT INTO tags (id, slug, name, kind, category_group_id, description, is_active) VALUES ('tag_audio_production', 'audio-production', 'Audio production', 'category', 'cat_music', 'Mix, master, separate stems, and edit recorded audio.', 1) ON CONFLICT(slug) DO UPDATE SET name = excluded.name, kind = excluded.kind, category_group_id = excluded.category_group_id, description = excluded.description, is_active = 1;--> statement-breakpoint
INSERT INTO tags (id, slug, name, kind, category_group_id, description, is_active) VALUES ('tag_sound_effects', 'sound-effects', 'Sound effects', 'category', 'cat_music', 'Generate or find sound effects and ambient audio.', 1) ON CONFLICT(slug) DO UPDATE SET name = excluded.name, kind = excluded.kind, category_group_id = excluded.category_group_id, description = excluded.description, is_active = 1;--> statement-breakpoint
INSERT INTO tags (id, slug, name, kind, category_group_id, description, is_active) VALUES ('tag_podcast_production', 'podcast-production', 'Podcast production', 'category', 'cat_music', 'Record, edit, and publish podcast episodes.', 1) ON CONFLICT(slug) DO UPDATE SET name = excluded.name, kind = excluded.kind, category_group_id = excluded.category_group_id, description = excluded.description, is_active = 1;--> statement-breakpoint
INSERT INTO tags (id, slug, name, kind, category_group_id, description, is_active) VALUES ('tag_study_assistant', 'study-assistant', 'Study assistant', 'category', 'cat_education', 'Help learners study, practise, and understand course material.', 1) ON CONFLICT(slug) DO UPDATE SET name = excluded.name, kind = excluded.kind, category_group_id = excluded.category_group_id, description = excluded.description, is_active = 1;--> statement-breakpoint
INSERT INTO tags (id, slug, name, kind, category_group_id, description, is_active) VALUES ('tag_language_learning', 'language-learning', 'Language learning', 'category', 'cat_education', 'Practise and learn new languages.', 1) ON CONFLICT(slug) DO UPDATE SET name = excluded.name, kind = excluded.kind, category_group_id = excluded.category_group_id, description = excluded.description, is_active = 1;--> statement-breakpoint
INSERT INTO tags (id, slug, name, kind, category_group_id, description, is_active) VALUES ('tag_course_creation', 'course-creation', 'Course creation', 'category', 'cat_education', 'Build lessons, quizzes, and courses for teaching.', 1) ON CONFLICT(slug) DO UPDATE SET name = excluded.name, kind = excluded.kind, category_group_id = excluded.category_group_id, description = excluded.description, is_active = 1;--> statement-breakpoint
INSERT INTO tags (id, slug, name, kind, category_group_id, description, is_active) VALUES ('tag_finance_accounting', 'finance-accounting', 'Finance & accounting', 'category', 'cat_business', 'Bookkeeping, invoicing, expenses, and financial analysis.', 1) ON CONFLICT(slug) DO UPDATE SET name = excluded.name, kind = excluded.kind, category_group_id = excluded.category_group_id, description = excluded.description, is_active = 1;--> statement-breakpoint
INSERT INTO tags (id, slug, name, kind, category_group_id, description, is_active) VALUES ('tag_recruiting', 'recruiting', 'Recruiting & HR', 'category', 'cat_business', 'Hiring, candidate screening, and people operations.', 1) ON CONFLICT(slug) DO UPDATE SET name = excluded.name, kind = excluded.kind, category_group_id = excluded.category_group_id, description = excluded.description, is_active = 1;--> statement-breakpoint
INSERT INTO tags (id, slug, name, kind, category_group_id, description, is_active) VALUES ('tag_sales_outreach', 'sales-outreach', 'Sales outreach', 'category', 'cat_marketing', 'Prospecting, outreach, and sales pipeline work.', 1) ON CONFLICT(slug) DO UPDATE SET name = excluded.name, kind = excluded.kind, category_group_id = excluded.category_group_id, description = excluded.description, is_active = 1;--> statement-breakpoint
INSERT INTO tags (id, slug, name, kind, category_group_id, description, is_active) VALUES ('tag_seo', 'seo', 'SEO', 'category', 'cat_marketing', 'Research, write, and optimise content for search visibility.', 1) ON CONFLICT(slug) DO UPDATE SET name = excluded.name, kind = excluded.kind, category_group_id = excluded.category_group_id, description = excluded.description, is_active = 1;--> statement-breakpoint
INSERT INTO tags (id, slug, name, kind, category_group_id, description, is_active) VALUES ('tag_travel_planning', 'travel-planning', 'Travel planning', 'category', 'cat_lifestyle', 'Plan trips, itineraries, and bookings.', 1) ON CONFLICT(slug) DO UPDATE SET name = excluded.name, kind = excluded.kind, category_group_id = excluded.category_group_id, description = excluded.description, is_active = 1;--> statement-breakpoint
INSERT INTO tags (id, slug, name, kind, category_group_id, description, is_active) VALUES ('tag_health_wellness', 'health-wellness', 'Health & wellness', 'category', 'cat_lifestyle', 'Fitness, nutrition, sleep, and personal wellbeing.', 1) ON CONFLICT(slug) DO UPDATE SET name = excluded.name, kind = excluded.kind, category_group_id = excluded.category_group_id, description = excluded.description, is_active = 1;
